version: '3'

services:
   gitlab:
     container_name: gitlab
     image: gitlab/gitlab-ce:13.3.9-ce.0
     networks:
       containers:
         ipv4_address: 192.168.1.240
     hostname: gitlab
     domainname: docker.muflone.lan
     restart: 'no'
     volumes:
       - ./config:/etc/gitlab
       - ./data:/var/opt/gitlab
       - ./logs:/var/log/gitlab

networks:
  containers:
    external: true

